baseURL: https://intelligencemodifier.com/
title: Intellegence Modifer
# Copyright, the {year} is the placeholder of this year.
copyright: "Copyright Â© 2022-{year} [Hugo Modules](https://hugomods.com/) and [HB Framework](https://hbstack.dev/). All Rights Reserved."
defaultContentLanguage: en
defaultContentLanguageInSubdir: false # when true, append the default language code into URL, i.e. /docs -> /en/docs.
enableRobotsTXT: true
timeout: 120s
enableEmoji: true

title_sections: true # when false, remove the sections from the title.
title_sections_depth: 0 # the depth of sections on the title.
title_sections_depth_dir: end # when start, the depth is counting from the root sections.

permalinks:
  blog: /blog/:year/:month/:title
  news: /news/:year/:month/:title

outputs:
  home:
    - HTML
    - Offline        # required by PWA module for displaying the offline pages.
    - RSS
    - SearchIndex    # required by search module.
    - WebAppManifest # required by PWA module to make your site installable.

taxonomies:
  authors: authors       # multiple authors.
  tags: tags
  categories: categories
  series: series

build:
  writeStats: true # required by PurgeCSS.

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    lineNos: true
    lineNumbersInTable: false

security:
  funcs:
    getenv:
      - ^HUGO
      - CI$
      - PWD
