# The order of module is very important, precedence from top to bottom.
imports:
  - path: github.com/hbstack/theme-cards
  - path: github.com/hbstack/google-fonts
  - path: github.com/hbstack/syntax-highlighting/styles/github-dark

  # icons modules
  - path: github.com/hugomods/icons/vendors/font-awesome
  # - path: github.com/hugomods/icons/vendors/mdi
  # - path: github.com/hugomods/icons/vendors/simple-icons
  # - path: github.com/hugomods/icons/vendors/tabler
  # - path: github.com/hugomods/icons/vendors/feather

  # blog
  - path: github.com/hbstack/blog/modules/sidebar/profile
#  - path: github.com/hbstack/blog/modules/sidebar/posts
#  - path: github.com/hbstack/blog/modules/sidebar/taxonomies
  - path: github.com/hbstack/blog/modules/utterances
  - path: github.com/hbstack/blog/modules/toc-scrollspy
  - path: github.com/hbstack/blog/modules/content-panel
  - path: github.com/hbstack/blog/modules/social-share-buttons

  # other modules
  # - path: github.com/hugomods/google-analytics
  # - path: github.com/hugomods/google-adsense

  # recommended modules
  # check which modules were imported by recommended module by "hugo mod graph | grep recommended".
  # see also https://hbstack.dev/en/docs/modules/meta/.
  # to remove unused modules, you need to replace the recommended module with modules your need.
  # see also https://hbstack.dev/en/2023/10/replace-meta-modules/.
  - path: github.com/hbstack/meta/recommended
