description:
hb:
  js_bundle_name: main # the JS bundle name.
  css_bundle_name: main # the CSS bundle name.
  full_width: false # when true, the layout takes full width globally.
  header:
    logo_bg: '#ffffff' # logo background color, used by logo with transparent background.
    socials:
      github: IntModifier
      linkedin: erstacey
      twitter: vYooper
      bluesky: vyooper.intmod.tech
      rss: true
  footer:
  blog:
    utterances:
      repo: IntModifier/IntModifier.github.io
    list_cols_md: 1
    list_cols_lg: 1
    toc:
      position: start # the toc position: start (left) or end (right).
    social_share_buttons:
      alignment: center
      media:
        - twitter
        - linkedin
    sidebar:
      sticky: true # set it to false to not stick the sidebar.
      width: .35 # the width of sidebar.
      position: start # the sidebar position: start (left) or end (right).
      profile:
        title: Eric Stacey
        description: Nerd.
        avatar: /images/me.jpeg
        avatar_size: 200
        socials:
          github: IntModifier
          linkedin: erstacey
          twitter: vYooper
          bluesky: vyooper.intmod.tech
          rss: true
    paginate: 10
    post_thumbnail: false # whether to show the thumbnails.
    home:
      taxonomies: false
      featured_posts: 0 
      pinned_posts_position: "list"
      main_sections:
        - blog
  google_fonts:
    families:
      - name: Lato

seo:
  favicons:
    icon: /images/logo.png

search:
  stall_threshold: 300
  min_match_char_length: 2
  case_sensitive: false

hugopress:
  modules:
    hb-custom:
      hooks:
        hb-blog-sidebar:
          cacheable: true
          weight: 1
